language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - secure: "C5R7AoxtNgOxVrgTpEEK6LKb7pjDbaU1Wa/buCnCPvKmjmbaIyJApxvLocLsQogsnGwCMiz/F7ZjugqaMUezKrPHEWG7agBQEwSxyKBJw8kgOyV9DeozKN0GklGRxr69y9X/LDPEvBk7LAfnJD8bmVFx2BUiZublItKvEvZX3H2W7qrwBBUH91KulrbeeYvcodcejVsl0EF8cSTQ0Va70Xlam6M9zoylzHtVBkuyjrg+S6CQ2AnvUaEYAMc2TmMJvrW2Yhz/vJ0nbS/44CnKOHjxyBsoHhouUDNdc8l/+cMKF1d7UEp6T12S/GBvV0R4ATPsUadbzb3uupkgi35N6Npc76RPQxVA2P5L8WEQDmZfbUsqUC1YLW5cXAcmDHrbn8O79Gt7GMpB8GzXlT4mgrRg0F4dYrVq/gvPwbHndbM1j8Aflrc/tQPYv4Ba5iv8vtWyvEJ7/UehbeoIAoKZCaYIBNV0JFHRH2UolwSEtRXbV6TPgkMvfDV2ZuyoAfw1/b1XJsrl6R52h5TgmPAQ50YnTI3BqJFNdvKOMErzz3Ti3hgOkS5OH4T4sKnvUa7vBvpHjO11TleAvHqdVDjXekth0gD1RT+iRQR+zp33bGXjqtSgnqTdtZO4H2bKrxUs2kZnFzs9afeiDOciQo+yi9IqhnW0gb259IqZUTdls9U="
